mkdir -p campus/section_01/00/video
mkdir -p campus/section_01/01/video

# wget https://mbzuaiac-my.sharepoint.com/:v:/g/personal/sebastian_cavada_mbzuai_ac_ae/EX8AQwFx6gFAuYbIxdSbLvMBPc3hz3lnFvtUZNCd7NNywA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=uXyffF&download=1 -o ./campus/section_01/00/video/GX010041.MP4
# wget https://mbzuaiac-my.sharepoint.com/:v:/g/personal/sebastian_cavada_mbzuai_ac_ae/EX8AQwFx6gFAuYbIxdSbLvMBPc3hz3lnFvtUZNCd7NNywA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=uXyffF&download=1 -o ./campus/section_01/01/video/GX010026.MP4

mkdir -p _data/campus_big_0.1fps
mkdir -p _data/campus_big_1.0fps
mkdir -p _data/campus_big_5.0fps
mkdir -p _data/campus_big_sparse
mkdir -p _data/campus_test


# campus 00      
wget 'https://mbzuaiac-my.sharepoint.com/:v:/g/personal/sebastian_cavada_mbzuai_ac_ae/EVS6AaAMhpdDjSCfQ1GQkbEBBVRk4FSK-D1Xjwt-n9aicA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=bpWowW&download=1' -O ./GX010049.MP4
#wget 'https://mbzuaiac-my.sharepoint.com/:v:/g/personal/sebastian_cavada_mbzuai_ac_ae/EacPKEGTlBJNmboa2p60YHMBsaddStZezFWpGDPZOxX4LA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=ImSGbI&download=1' -O ./GX020049.MP4

# campus 01
#wget 'https://mbzuaiac-my.sharepoint.com/:v:/g/personal/sebastian_cavada_mbzuai_ac_ae/EfKk9e8X_D1ErlhPIPgRG28BOLGR5HBNBoZVkGu1MW2gpw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=r77zJ2&download=1' -O ./GX010044.MP4
#wget 'https://mbzuaiac-my.sharepoint.com/:v:/g/personal/sebastian_cavada_mbzuai_ac_ae/EeOe87ehripBiGNQD_IcnVABFTblBAM8mIp_Bw6AfaRo_w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=84Ao91&download=1' -O ./GX020044.MP4
